print("----- And Operator -----")
print(True and True)
print(True and False)
print(False and True)
print(False and False)
print("----- Or Operator -----")
print(True or True)
print(True or False)
print(False or True)
print(False or False)
print("----- Testing -----")
print(10>10)
print(10>=10)
print(10!=9)
print(10==10)